Story_5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Story_5_app.urls')),
]

Story_5_app/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = "Story_5_app" 

urlpatterns = [
	path ('admin/', admin.site.urls),
	path ('', views.homepage, name='homepage'),
	path ('createJadwal/', views.create_jadwal, name='createJadwal'),
	path ('delete/', views.delete, name="delete")
]

Story_5_app/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=25)
    kategori = models.CharField(null=True, max_length=25)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

Story_5_app/forms.py
from . import models
from django import forms
import datetime

class JadwalForm(forms.ModelForm):
        nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Nama Kegiatan",
                }))
        tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Tempat",
                }))
        kategori = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Kategori",
                }))
        tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }), initial=datetime.datetime.now() )
        waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }), initial=datetime.datetime.now() ) 

        class Meta:
                model = models.Jadwal
                fields = ["nama_kegiatan", "kategori", "tempat", "tanggal", "waktu"]

Story_5_app/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Jadwal
from django.utils import timezone
from .forms import JadwalForm
import datetime

# Create your views here.
def homepage(request):
	semua_jadwal = Jadwal.objects.all()
	return render(request, 'Homepage.html', {"jadwal": semua_jadwal})

def create_jadwal(request):
    form = JadwalForm()
    if request.method =="POST":
        form=JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('Story_5_app:createJadwal')
    return render(request, "Create Jadwal.html", {'form':form})

def jadwal(request):
    jadwals = Jadwal.objects.order_by("tanggal", "waktu")
    response = {
        'jadwal' : jadwals,
        'server_time' : datetime.datetime.now(),
    }
    return render(request, "Create Jadwal.html", response)

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Jadwal.objects.get(id=id).delete()
    return redirect('Story_5_app:homepage')

templates/Create Jadwal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'css/Homepage.css' %}">
    <title>Create Jadwal</title>
</head>
<body class="form-body">
    <div class="form-cont">
        <h2>Buat Jadwal</h2>
        <form method="POST" class="form">
            {% csrf_token %}
            <p>Nama Kegiatan</p>
            {{ form.nama_kegiatan }}
            <p>Tempat</p>
            {{ form.tempat }}
            <p>Kategori</p>
            {{ form.kategori }}
            <p>Waktu & Tanggal</p>
            <p>
                {{ form.tanggal }}
                {{ form.waktu }}
            </p>
            <div class="full">
                <a href="{% url 'Story_5_app:homepage' %}"><button type="button" class="button delete">Back</button></a>
                <input type="submit" class="button" value="Submit" />
            </div>
        </form>
    </div>
</body>
</html>

templates/Homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'css/Homepage.css' %}">
    <title>Homepage</title>
</head>
<body>
    <div class="container">
        <h1>Jadwal!!!!!!!</h1>
        
        <a href="createJadwal">
            <button class="button">Create Jadwal</button>
        </a>
            
        {% for j in jadwal %}
            <div class="jadwal-card">
                <h2><span>{{ j.kategori }}</span> - {{ j.nama_kegiatan }}</h2>
                <div class="flex">
                    <div>
                        <h4>di {{ j.tempat }}</h4>
                        <p>{{ j.tanggal }} - {{ j.waktu }}</p>
                    </div>
                    <form action="{% url 'Story_5_app:delete' %}" method="POST" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ j.id }}" name="id" />
                        <input class="button delete" type="submit" value="Delete" />
                    </form>
                </div>
            </div>
        {% endfor %}

    </div>
</body>
</html>